#' Read DAS file
#'
#' Read fixed-width DAS textfile generated by WinCruz
#'
#' @param file filename of a DAS file
#'
#' @importFrom lubridate year
#' @importFrom lubridate month
#' @importFrom lubridate day
#' @importFrom lubridate hour
#' @importFrom lubridate minute
#'
#' @details Read...
#'   Adapted from \code{\link[swfscMisc]{das.read}}
#'  TODO: describe columns created?
#'  TODO: any error checking?
#'
#' @return Data frame with columns for each DAS item...; idx_line only column added
#'   Processing done: create DateTime column and convert lat/lon to decimal;
#'   all else simply reading data from columns
#'   TODO: make return object of class das_read?
#'
#' @examples
#' # TODO
#' # x <- das_read("../das/Data/RV-Data/1986/MOPS0989.das")
#'
#' @export
das_read <- function(file) {
  #----------------------------------------------------------------------------
  # Parse and format DAS file

  ### Read file and get initial details
  DAS <- readLines(file)
  Event <- substr(DAS, 4, 4)
  nDAS <- length(DAS)
  OnEffort <- (substr(DAS, 5, 5) == ".")

  ### Format times and dates
  time.txt <- substr(DAS, 6, 11)
  time.txt <- gsub(" ", "", time.txt)
  date.txt <- substr(DAS, 13, 18)
  date.txt <- gsub(" ", "", date.txt)

  DateTime <- strptime(paste(date.txt, time.txt), "%m%d%y %H%M%S")
  dt.na <- is.na(DateTime)
  DateTime[dt.na] <- strptime(paste(date.txt, time.txt), "%m%d%y %H%M")[dt.na]

  dt.na <- is.na(DateTime)
  if (!all(names(table(Event[dt.na])) %in% c("*", "#", "?", "C", 1:8))) {
    warning("There are DateTime NAs for unexpected events, meaning for ",
            "events that are not one of: ", c("*", "#", "?", "C", 1:8))
  }

  ### Get lat/long info
  LatD <- as.numeric(substr(DAS, 21, 22))
  LatM <- as.numeric(substr(DAS, 24, 28))
  LonD <- as.numeric(substr(DAS, 31, 33))
  LonM <- as.numeric(substr(DAS, 35, 39))
  Lat <- (LatD + LatM/60) * ifelse(substr(DAS, 20, 20) == "S", -1, 1)
  Lon <- (LonD + LonM/60) * ifelse(substr(DAS, 30, 30) == "W", -1, 1)
  rm(LatD, LatM, LonD, LonM)

  lat.na <- which(is.na(Lat))
  lon.na <- which(is.na(Lon))
  if (!(all.equal(lon.na, lat.na) == TRUE)) {
    warning("The Lon and Lat columns have NA values for different rows")
  }

  ### Get data (i.e. field) info
  Data1 <- gsub(" ", "", substr(DAS, 40, 44))
  Data1[Data1 == ""] <- NA
  Data2 <- gsub(" ", "", substr(DAS, 45, 49))
  Data2[Data2 == ""] <- NA
  Data3 <- gsub(" ", "", substr(DAS, 50, 54))
  Data3[Data3 == ""] <- NA
  Data4 <- gsub(" ", "", substr(DAS, 55, 59))
  Data4[Data4 == ""] <- NA
  Data5 <- gsub(" ", "", substr(DAS, 60, 64))
  Data5[Data5 == ""] <- NA
  Data6 <- gsub(" ", "", substr(DAS, 65, 69))
  Data6[Data6 == ""] <- NA
  Data7 <- gsub(" ", "", substr(DAS, 70, 74))
  Data7[Data7 == ""] <- NA
  Data8 <- gsub(" ", "", substr(DAS, 75, 79))
  Data8[Data8 == ""] <- NA


  #----------------------------------------------------------------------------
  # Return data frame
  data.frame(
    Event, OnEffort, DateTime,
    Yr = as.numeric(year(DateTime)), Mo = as.numeric(month(DateTime)),
    Da = as.numeric(day(DateTime)),
    Hr = as.numeric(hour(DateTime)), Min = as.numeric(minute(DateTime)),
    Lat, Lon,
    Data1, Data2, Data3, Data4, Data5, Data6, Data7, Data8,
    idx_line = 1:nDAS,
    stringsAsFactors = FALSE
  )
}
