#' Read DAS file(s)
#'
#' Read one or more fixed-width DAS text file(s) generated by WinCruz into a data frame,
#'   where each line is data for a specific event
#'
#' @param file filename(s) of one or more DAS files
#' @param tz character; see \link[base]{strptime}. Default is UTC
#'
#' @details Reads/parses DAS data into columns of a data frame.
#'   If \code{file} contains multiple filenames, then the individual
#'   data frames will be concatenated.
#'
#'   The provided DAS file must adhere to the following column number and format specifications;
#'   note that 'Data#' columns may be referred to as 'Field#' columns in other documentation:
#'   \tabular{lrr}{
#'     \emph{Item}  \tab \emph{Columns} \tab \emph{Format}\cr
#'     Event number \tab 1-3\cr
#'     Event        \tab 4\cr
#'     Effort dot   \tab 5\cr
#'     Time         \tab 6-11  \tab HHMMSS or HHMM\cr
#'     Date         \tab 13-18 \tab MMDDYY\cr
#'     Latitude     \tab 20-28 \tab NDD:MM.MM\cr
#'     Longitude    \tab 30-39 \tab WDDD:MM.MM\cr
#'     Data1        \tab 40-44\cr
#'     Data2        \tab 45-49\cr
#'     Data3        \tab 50-54\cr
#'     Data4        \tab 55-59\cr
#'     Data5        \tab 60-64\cr
#'     Data6        \tab 65-69\cr
#'     Data7        \tab 70-74\cr
#'     Data8        \tab 75-79\cr
#'     Data9        \tab 80+\cr
#'   }
#'
#'   See \code{\link{das_format_pdf}} for more information about DAS format requirements.
#'   This function was inspired by \code{\link[swfscMisc]{das.read}}
#'
#' @return A \code{das_dfr} object, which is also a data frame, with DAS data read into columns.
#'   The data are read into the data frame as characters as described in 'Details',
#'   with the following exceptions:
#'   \tabular{lll}{
#'     \emph{Name} \tab \emph{Class} \tab \emph{Details}\cr
#'     EffortDot \tab logical   \tab \code{TRUE} if "." was present, and \code{FALSE} otherwise\cr
#'     DateTime  \tab POSIXct   \tab combination of 'Date' and 'Time' columns with time zone \code{tz}\cr
#'     Lat       \tab numeric   \tab 'Latitude' column converted to decimal degrees in range [-90, 90]\cr
#'     Lon       \tab numeric   \tab 'Longitude' column converted to decimal degrees in range [-180, 180]\cr
#'     Data#     \tab character \tab leading/trailing whitespace trimmed for non-comment events (i.e. rows where 'Event' is not "C" or "c")\cr
#'     EventNum  \tab character \tab leading/trailing whitespace trimmed; left as character for some special, project-specific codes\cr
#'     file_das  \tab character \tab filename, extracted from the \code{file} argument using \code{\link[base]{basename}}\cr
#'     line_num  \tab integer   \tab line number of each data row\cr
#'   }
#'
#'   Warnings are printed if any unexpected events have \code{NA} DateTime/Lat/Lon values,
#'   or if any Lat/Lon values cannot be converted to numeric values.
#'   Events that are 'expected' to have \code{NA} DateTime/Lat/Lon values are:
#'   C, ?, 1, 2, 3, 4, 5, 6, 7, 8
#'
#' @seealso For more details about WinCruz, see
#'   \url{https://swfsc.noaa.gov/uploadedFiles/Divisions/PRD/WinCruz.pdf}
#'
#' @examples
#' y <- system.file("das_sample.das", package = "swfscDAS")
#' das_read(y)
#'
#' @export
das_read <- function(file, tz = "UTC") {
  stopifnot(inherits(file, "character"))

  if (length(file) < 1)
    stop("file must be a vector of one or more filename(s)")

  if (!all(file.exists(file)))
    stop("The supplied character string(s) does (do) not (all) name ",
         "an existing file(s), ",
         "aka file.exists(file) is FALSE")

  do.call(rbind, lapply(file, .das_read, tz = tz))
}


.das_read <- function(file, tz) {
  # Input checks
  stopifnot(inherits(file, "character"))

  # Start and end (inclusive) column indices
  fwf.start <- c(1,4,5, 06,13, 20,21,24, 30,31,35, 40,45,50,55,60,65,70,75,80)
  fwf.end   <- c(3,4,5, 11,18, 20,22,28, 30,33,39, 44,49,54,59,64,69,74,79,NA)

  # suppressWarnings() is for lines that do not have data in all columns
  x <- suppressWarnings(read_fwf(
    file, col_positions = fwf_positions(start = fwf.start, end = fwf.end),
    skip_empty_rows = FALSE,
    na = c("", " ", "  ", "   ", "    ", "     ", "      "),
    col_types = cols(.default = col_character()),
    trim_ws = FALSE
  ))

  names(x) <- c(
    "EventNum", "Event", "EffortDot", "Time", "Date",
    "Lat1", "Lat2", "Lat3", "Lon1", "Lon2", "Lon3",
    "Data1", "Data2", "Data3", "Data4", "Data5", "Data6", "Data7", "Data8", "Data9"
  )

  # Process data, and add file and line number columns
  x$EffortDot <- ifelse(is.na(x$EffortDot), FALSE, TRUE)
  EventNum <- trimws(x$EventNum)
  file_das  <- basename(file)
  line_num  <- seq_along(x$Event)

  # Convert lat and lon values to decimal degrees
  Lat <- ifelse(x$Lat1 == "N", 1, -1) * (as.numeric(x$Lat2) + as.numeric(x$Lat3)/60)
  Lon <- ifelse(x$Lon1 == "E", 1, -1) * (as.numeric(x$Lon2) + as.numeric(x$Lon3)/60)

  # Print warning if unable to coerce lat/lon to numeric
  ll.num.na <- unique(
    c(.numeric_na(x$Lat2), .numeric_na(x$Lat3),
      .numeric_na(x$Lon2), .numeric_na(x$Lon3))
  )
  if (length(ll.num.na) > 0)
    warning("The following rows have values in the Latitude and/or Longitude ",
            "columns that could not be converted to a numeric value:\n",
            paste(ll.num.na, collapse = ", "))
  rm(ll.num.na)


  # Lat/lon NA check
  ll.na <- is.na(Lat) | is.na(Lon)
  ll.na.event <- c("C", "?", 1:8)
  ll.na.which <- which((!(x$Event %in% ll.na.event)) & ll.na)
  if (length(ll.na.which) > 0) {
    warning("There are unexpected (i.e. for events other than ",
            paste(ll.na.event, collapse = ", "),
            ") Lat and/or Lon NAs in row(s):\n",
            paste(ll.na.which, collapse = ", "))
  }
  rm(ll.na, ll.na.event, ll.na.which)

  # Extract date/time
  DateTime <- strptime(paste(x$Date, x$Time), "%m%d%y %H%M%S", tz)
  dt.na <- is.na(DateTime)
  DateTime[dt.na] <- strptime(paste(x$Date, x$Time), "%m%d%y %H%M", tz)[dt.na]
  dt.na <- is.na(DateTime)

  # Datetime NA check
  dt.na.event <- c("*", "#", "?", "C", 1:8)
  dt.na.which <- which((!(x$Event %in% dt.na.event) & dt.na))
  if (length(dt.na.which) > 0) {
    warning("There are unexpected (i.e. for events other than ",
            paste(dt.na.event, collapse = ", "),
            ") DateTime NAs in row(s):\n",
            paste(dt.na.which, collapse = ", "))
  }
  rm(dt.na, dt.na.event, dt.na.which)

  # Extract Data# values, and trim whitespace as necessary
  data.df <- data.frame(
    Data1 = ifelse(x$Event == "C", x$Data1, trimws(x$Data1)),
    Data2 = ifelse(x$Event == "C", x$Data2, trimws(x$Data2)),
    Data3 = ifelse(x$Event == "C", x$Data3, trimws(x$Data3)),
    Data4 = ifelse(x$Event == "C", x$Data4, trimws(x$Data4)),
    Data5 = ifelse(x$Event == "C", x$Data5, trimws(x$Data5)),
    Data6 = ifelse(x$Event == "C", x$Data6, trimws(x$Data6)),
    Data7 = ifelse(x$Event == "C", x$Data7, trimws(x$Data7)),
    Data8 = ifelse(x$Event == "C", x$Data8, trimws(x$Data8)),
    Data9 = ifelse(x$Event == "C",
                   ifelse(trimws(x$Data9) == "", NA, x$Data9),
                   trimws(x$Data9)),
    stringsAsFactors = FALSE
  )
  # Data9 extra ^ is for entries with >6 spaces (eg "       ")
  data.df[data.df == ""] <- NA

  # Coerce data frame to das_dfr object and return
  as_das_dfr(data.frame(
    Event = x$Event, EffortDot = x$EffortDot, DateTime, Lat, Lon, data.df,
    EventNum, file_das, line_num,
    stringsAsFactors = FALSE
  ))
}
